// @vitest-environment node
/**
 * E5 — the SEEDED batch path of the off-main-thread keygen (`runSeededBatch`).
 *
 * A seeded run derives RSA-4096 keys deterministically from a 1600-bit DALOS
 * bitstring at the indices `planIndexRanges` selected. At the measured ~6.7 s
 * PER KEY, a 100-position run is ~11 minutes of CPU — which fixes what these
 * cases have to guard:
 *
 *   - Keys must reach `onKey` AS THEY ARRIVE. If the runner buffered them until
 *     the batch terminal, a cancel or a closed tab would throw away hours of
 *     completed prime searches. That is the regression case (a) catches.
 *   - An abort must stop delivery, and must NOT roll back what was already
 *     handed over — case (b).
 *   - Index 0 is force-generated by `rsa4096/ranges.js` on EVERY call
 *     (`const seen = new Set([0])`) regardless of `ranges`. The runner must
 *     therefore pass it to `onKey` like any other index and let the CALLER apply
 *     the never-clobber guard at storage. A runner that "helpfully" filtered
 *     index 0 would silently lose a legitimately new #0 — case (f).
 *
 * NO real Worker and NO real RSA: jsdom/node have no `Worker`, and real
 * generation would make this suite unusable. Everything is driven through an
 * INJECTED `workerFactory` returning a fake worker that emits typed
 * `KeygenWorkerMsg` values — the same idiom `e4-keygen-runner.test.ts` uses.
 *
 * `// @vitest-environment node`: message plumbing only, no DOM.
 */

import { describe, it, expect, vi } from "vitest";

// TYPE-ONLY (erased at compile time — the heavy RSA surface is never loaded
// here): the rich progress event is the LIBRARY's own `BatchProgressEvent`,
// asserted against the exported type rather than a local re-declaration, so a
// library field rename breaks the build instead of silently drifting.
import type { BatchProgressEvent } from "@ouronet/dalos-crypto/rsa4096";

// `runSeededBatch` is imported from its MODULE, not the `src/keygen` barrel:
// the barrel is owned by another task and is not re-exporting it yet. The
// pre-existing random path is exercised through the public barrel, which is
// exactly how its consumers reach it.
import {
  runSeededBatch,
  type SeededKey,
} from "../src/keygen/KeygenRunner";
import {
  createWorkerKeygenRunner,
  type KeygenWorkerMsg,
  type KeygenProgress,
} from "../src/keygen";

import { throwawayJwk } from "./e3-helpers";

/** A minimal FAKE `Worker` the test drives message-by-message — mirrors the
 *  `FakeWorker` in `e4-keygen-runner.test.ts` (not a real Web Worker). */
class FakeWorker {
  onmessage: ((ev: { data: KeygenWorkerMsg }) => void) | null = null;
  onerror: ((ev: unknown) => void) | null = null;
  posted: unknown[] = [];
  terminated = false;
  postMessage(msg: unknown): void {
    this.posted.push(msg);
  }
  terminate(): void {
    this.terminated = true;
  }
  emit(data: KeygenWorkerMsg): void {
    this.onmessage?.({ data });
  }
}

/** A 1600-bit stand-in seed — the runner only forwards it to the worker. */
const BITS = "1".repeat(1600);

/** A `key` message for `index`, carrying the throwaway fixture JWK. */
function keyMsg(index: number): KeygenWorkerMsg {
  return {
    kind: "key",
    index,
    jwk: throwawayJwk,
    address: `address-${index}`,
  };
}

describe("runSeededBatch — per-key delivery (E5, ~6.7 s/key)", () => {
  it("(a) hands EVERY key to onKey as it arrives, in order, BEFORE the batch terminal — never buffered to the end", async () => {
    const worker = new FakeWorker();
    const delivered: SeededKey[] = [];
    const progress: KeygenProgress[] = [];

    const run = runSeededBatch({
      bits: BITS,
      ranges: [
        { start: 0, end: 0 },
        { start: 1, end: 1 },
      ],
      workerFactory: () => worker as unknown as Worker,
      onKey: (key) => delivered.push(key),
      onProgress: (p) => progress.push(p),
    });

    worker.emit({ kind: "progress", state: { state: "working" } });
    worker.emit(keyMsg(0));
    // The key is delivered on the message, NOT held until the run settles.
    expect(delivered.map((k) => k.index)).toEqual([0]);

    worker.emit(keyMsg(1));
    expect(delivered.map((k) => k.index)).toEqual([0, 1]);

    worker.emit({ kind: "batch-done" });

    await expect(run).resolves.toEqual({ delivered: 2, cancelled: false });
    expect(delivered.map((k) => k.address)).toEqual(["address-0", "address-1"]);
    expect(progress.map((p) => p.state)).toEqual(["working"]);
    expect(worker.terminated).toBe(true);
  });

  it("(a-wiring) sends the seed bitstring and the planned ranges to the worker, so the worker generates the requested indices and not a random key", () => {
    const worker = new FakeWorker();
    const ranges = [{ start: 0, end: 0 }, { start: 4, end: 7 }];

    void runSeededBatch({
      bits: BITS,
      ranges,
      workerFactory: () => worker as unknown as Worker,
      onKey: () => {},
    });

    expect(worker.posted).toEqual([
      { kind: "start-seeded", bits: BITS, ranges },
    ]);
  });

  it("(f) delivers index 0 like any other index — the library force-generates it regardless of `ranges`, and the never-clobber decision belongs to the CALLER", async () => {
    const worker = new FakeWorker();
    const delivered: SeededKey[] = [];

    const run = runSeededBatch({
      bits: BITS,
      // Index 0 is NOT requested — the library adds it anyway.
      ranges: [{ start: 3, end: 3 }],
      workerFactory: () => worker as unknown as Worker,
      onKey: (key) => delivered.push(key),
    });

    worker.emit(keyMsg(0));
    worker.emit(keyMsg(3));
    worker.emit({ kind: "batch-done" });
    await run;

    expect(delivered.map((k) => k.index)).toEqual([0, 3]);
  });
});

describe("runSeededBatch — cancellation (E5)", () => {
  it("(b) aborting mid-stream stops delivery and does NOT roll back the keys already handed over", async () => {
    const controller = new AbortController();
    const worker = new FakeWorker();
    const delivered: SeededKey[] = [];

    const run = runSeededBatch({
      bits: BITS,
      ranges: [{ start: 0, end: 2 }],
      workerFactory: () => worker as unknown as Worker,
      onKey: (key) => delivered.push(key),
      signal: controller.signal,
    });

    worker.emit(keyMsg(0));
    worker.emit(keyMsg(1));
    expect(delivered.map((k) => k.index)).toEqual([0, 1]);

    controller.abort();

    // Anything the worker still had in flight is dropped, not delivered.
    worker.emit(keyMsg(2));

    await expect(run).resolves.toEqual({ delivered: 2, cancelled: true });
    // The already-delivered keys survive the cancel — that is the whole point.
    expect(delivered.map((k) => k.index)).toEqual([0, 1]);
    // The worker is stopped, so no further multi-second searches are paid for.
    expect(worker.terminated).toBe(true);
  });

  it("(b-pre) a signal already aborted before the call never constructs a worker — no CPU is burned on a run the user has cancelled", async () => {
    const controller = new AbortController();
    controller.abort();
    const workerFactory = vi.fn(() => new FakeWorker() as unknown as Worker);

    await expect(
      runSeededBatch({
        bits: BITS,
        ranges: [{ start: 0, end: 0 }],
        workerFactory,
        onKey: () => {},
        signal: controller.signal,
      }),
    ).resolves.toEqual({ delivered: 0, cancelled: true });

    expect(workerFactory).not.toHaveBeenCalled();
  });

  it("(b-worker) a worker-sent { kind: 'cancelled' } terminal settles the run instead of leaving the promise pending forever", async () => {
    const worker = new FakeWorker();
    const delivered: SeededKey[] = [];

    const run = runSeededBatch({
      bits: BITS,
      ranges: [{ start: 0, end: 5 }],
      workerFactory: () => worker as unknown as Worker,
      onKey: (key) => delivered.push(key),
    });

    worker.emit(keyMsg(0));
    worker.emit({ kind: "cancelled" });

    await expect(run).resolves.toEqual({ delivered: 1, cancelled: true });
    expect(worker.terminated).toBe(true);
  });
});

describe("runSeededBatch — failure (E5)", () => {
  it("(c) a { kind: 'error' } message REJECTS the run with that message", async () => {
    const worker = new FakeWorker();
    const run = runSeededBatch({
      bits: BITS,
      ranges: [{ start: 0, end: 0 }],
      workerFactory: () => worker as unknown as Worker,
      onKey: () => {},
    });

    worker.emit({ kind: "error", message: "seeded keygen failed in worker" });

    await expect(run).rejects.toThrow(/seeded keygen failed in worker/);
    expect(worker.terminated).toBe(true);
  });

  it("(c-hygiene) the rejection carries no key material — nothing the main thread posted contains the private exponent", async () => {
    const worker = new FakeWorker();
    const run = runSeededBatch({
      bits: BITS,
      ranges: [{ start: 0, end: 0 }],
      workerFactory: () => worker as unknown as Worker,
      onKey: () => {},
    });

    worker.emit(keyMsg(0));
    worker.emit({ kind: "error", message: "boom" });

    await expect(run).rejects.toThrow(/boom/);
    expect(JSON.stringify(worker.posted)).not.toContain(throwawayJwk.d);
  });

  it("(c-onerror) a worker-level error event rejects the run", async () => {
    const worker = new FakeWorker();
    const run = runSeededBatch({
      bits: BITS,
      ranges: [{ start: 0, end: 0 }],
      workerFactory: () => worker as unknown as Worker,
      onKey: () => {},
    });

    worker.onerror?.({});

    await expect(run).rejects.toThrow(/worker/i);
  });
});

describe("the pre-existing RANDOM keygen path is unaffected by the seeded extension (E5)", () => {
  it("(d) createWorkerKeygenRunner still resolves the JWK from a { kind: 'done' } message", async () => {
    const worker = new FakeWorker();
    const runner = createWorkerKeygenRunner({
      workerFactory: () => worker as unknown as Worker,
    });

    const seen: KeygenProgress[] = [];
    const done = runner.runKeygen((p) => seen.push(p));

    worker.emit({ kind: "progress", state: { state: "working" } });
    worker.emit({ kind: "done", jwk: throwawayJwk });

    await expect(done).resolves.toEqual(throwawayJwk);
    expect(seen.map((p) => p.state)).toEqual(["working"]);
    // The random path still starts with the plain `start` message.
    expect(worker.posted).toEqual([{ kind: "start" }]);
  });
});

describe("runSeededBatch — RICH batch progress (E5)", () => {
  /**
   * The library reports a full `BatchProgressEvent` after every candidate draw.
   * Flattening it to the coarse `{ state: "working" }` is exactly the bug this
   * guards: the UI progress line shows which index is being searched, the `p`/`q`
   * stage, the candidate-draw count, the 0..1 fraction and the `n / total`
   * counter — all of which vanish if any field is dropped or renamed on the way
   * through the worker message and the runner callback. The shipped Crypto Lab
   * (`StoicDigest/src/pages/lab/seed.astro`) consumes precisely these fields.
   */
  it("(g) forwards a { kind: 'batch-progress' } event VERBATIM to onBatchProgress — index, stage, attempts, overallProgress, completedCount and totalCount all intact", async () => {
    const worker = new FakeWorker();
    const events: BatchProgressEvent[] = [];

    const run = runSeededBatch({
      bits: BITS,
      ranges: [{ start: 0, end: 3 }],
      workerFactory: () => worker as unknown as Worker,
      onKey: () => {},
      onBatchProgress: (ev) => events.push(ev),
    });

    const ev: BatchProgressEvent = {
      index: 2,
      completedCount: 1,
      totalCount: 4,
      addressProgress: 0.5,
      overallProgress: 0.375,
      stage: "q",
      attempts: 412,
    };
    worker.emit({ kind: "batch-progress", ev });
    // Delivered on the message, not held until the run settles — the progress
    // line has to move DURING the ~6.7 s-per-key search, not after it.
    expect(events).toEqual([ev]);

    worker.emit({ kind: "batch-done" });
    await run;

    expect(events).toHaveLength(1);
    const [seen] = events;
    expect(seen.index).toBe(2);
    expect(seen.stage).toBe("q");
    expect(seen.attempts).toBe(412);
    expect(seen.overallProgress).toBeCloseTo(0.375);
    expect(seen.completedCount).toBe(1);
    expect(seen.totalCount).toBe(4);
  });

  /**
   * `onBatchProgress` is OPTIONAL: every caller written before this channel
   * existed omits it. An unguarded call would throw inside `onmessage`, which
   * for a fake worker propagates into the emitting code and in a real worker
   * would kill the run mid-batch — losing every completed prime search.
   */
  it("(g-optional) a run that omits onBatchProgress ignores batch-progress messages instead of throwing, and still settles normally", async () => {
    const worker = new FakeWorker();
    const delivered: SeededKey[] = [];

    const run = runSeededBatch({
      bits: BITS,
      ranges: [{ start: 0, end: 0 }],
      workerFactory: () => worker as unknown as Worker,
      onKey: (key) => delivered.push(key),
    });

    expect(() => {
      worker.emit({
        kind: "batch-progress",
        ev: {
          index: 0,
          completedCount: 0,
          totalCount: 1,
          addressProgress: 0.25,
          overallProgress: 0.25,
          stage: "p",
          attempts: 97,
        },
      });
    }).not.toThrow();

    worker.emit(keyMsg(0));
    worker.emit({ kind: "batch-done" });

    await expect(run).resolves.toEqual({ delivered: 1, cancelled: false });
  });

  /**
   * The two progress channels are independent and must stay that way: the coarse
   * `progress` states drive the run's phase (the UI's start/working/done
   * machine), the rich events drive the numbers. Routing either into the other's
   * callback would corrupt both consumers, and the coarse channel is consumed
   * TODAY.
   */
  it("(g-separate) keeps the coarse progress channel and the rich batch-progress channel separate — neither leaks into the other's callback", async () => {
    const worker = new FakeWorker();
    const coarse: KeygenProgress[] = [];
    const rich: BatchProgressEvent[] = [];

    const run = runSeededBatch({
      bits: BITS,
      ranges: [{ start: 0, end: 0 }],
      workerFactory: () => worker as unknown as Worker,
      onKey: () => {},
      onProgress: (p) => coarse.push(p),
      onBatchProgress: (ev) => rich.push(ev),
    });

    worker.emit({ kind: "progress", state: { state: "working" } });
    worker.emit({
      kind: "batch-progress",
      ev: {
        index: 0,
        completedCount: 0,
        totalCount: 1,
        addressProgress: 0.1,
        overallProgress: 0.1,
        stage: "p",
        attempts: 33,
      },
    });
    worker.emit({ kind: "progress", state: { state: "done" } });
    worker.emit({ kind: "batch-done" });
    await run;

    expect(coarse.map((p) => p.state)).toEqual(["working", "done"]);
    expect(rich.map((e) => e.attempts)).toEqual([33]);
  });
});
