#!/usr/bin/env python3
"""Emit src/constants/pactSignatures.generated.ts — every Talos client entrypoint's parameters.

WHY THIS PACKAGE NEEDS IT AT RUNTIME. The execution tooltip (`zbom/cfm/ExecutionTooltip.tsx`)
shows a button's real API before you press it: function name, parameter list, then the live
INFO preview run against ghost values. The parameter list has to come from the CONTRACT, not
from a hand-kept copy — a hand-kept copy drifts exactly the way this package's own builders
drifted (see the 2026-09-26 "complete rehaul" round: `C_ReleaseStoicTag`/`C_RegisterStoicTag`/
`C_RotateKadena`→`C_RotateStoa`/etc., all found by comparing against `describe-module` output
one function at a time over the network). Reading straight from the `.pact` sources gives the
SAME answer offline, for every function at once, and lets the checker (`check-call-sites.py`)
run in CI without a network call.

Ported from `daimons/OuronetUI/scripts/generate-pact-signatures.py` (sibling repo,
OuroborosNetwork workspace) — same approach, repointed at this workspace's own Pact source tree
and this package's own bundle boundary.

    python3 scripts/generate-pact-signatures.py [path-to-onchain-Ouronet]

Regenerate whenever the Pact sources change or a chain-symbol audit lands. The default source
path assumes the sibling-repo layout this workspace uses
(`OuroborosNetwork/_onchain/Ouronet` next to `AncientPantheon/constructors/Codex`) — pass an
explicit path as the first argument to override.
"""
import json
import os
import pathlib
import re
import sys

PKG = pathlib.Path(__file__).resolve().parent.parent  # packages/codex-ouronet

# Default: sibling-repo layout — .../ClaudeWS/{AncientPantheon,OuroborosNetwork}/...
# PKG = .../ClaudeWS/AncientPantheon/constructors/Codex/packages/codex-ouronet
DEFAULT_PACT = (
    PKG.parent.parent.parent.parent.parent  # .../ClaudeWS
    / "OuroborosNetwork" / "_onchain" / "Ouronet"
)
PACT = pathlib.Path(sys.argv[1]).expanduser().resolve() if len(sys.argv) > 1 else DEFAULT_PACT

OUT = PKG / "src/constants/pactSignatures.generated.ts"   # bundled: tooltip only
FULL = PKG / "scripts/pact-signatures.full.json"           # not bundled: the checker

# EVERY function a client could call, not just the Talos entrypoints — see the sibling script's
# own note: a reader named wrong breaks a page exactly as thoroughly as a wrong entrypoint, and
# scoping the manifest to writes is what let this package's own `UR_AccountKadena` /
# `INFO-ZERO.DALOS-INFO|URC_*` bugs go undetected by any static tool.
WANTED = re.compile(r'^[A-Za-z][A-Za-z0-9|_-]*$')


def params_at(text, idx):
    i = text.index("(", idx)
    depth, j = 0, i
    while j < len(text):
        if text[j] == "(":
            depth += 1
        elif text[j] == ")":
            depth -= 1
            if depth == 0:
                break
        j += 1
    return re.findall(r'([a-z][A-Za-z0-9-]*)\s*:', text[i:j + 1])


def main():
    if not PACT.is_dir():
        print(f"error: Pact source tree not found at {PACT}")
        print("       pass the correct path as the first argument:")
        print("       python3 scripts/generate-pact-signatures.py /path/to/_onchain/Ouronet")
        return 1

    sigs = {}
    roots = []
    for sub in ("1_SOVEREIGN", "2_CITIZEN"):
        d = PACT / sub
        if d.is_dir():
            roots += list(d.rglob("*.pact"))
    if not roots:
        print(f"error: no .pact files found under {PACT}/1_SOVEREIGN or {PACT}/2_CITIZEN")
        return 1

    for f in roots:
        text = f.read_text(encoding="utf8", errors="replace")
        for mod in re.finditer(r'^\(module\s+([A-Za-z0-9|_-]+)\s', text, re.M):
            body = text[mod.start():]
            for d in re.finditer(r'\n\s{1,8}\(defun\s+([^\s:(]+)', body):
                fn = d.group(1)
                if not WANTED.match(fn):
                    continue
                key = f"{mod.group(1)}.{fn}"
                if key in sigs:
                    continue
                sigs[key] = params_at(body, d.end())

    # TWO ARTIFACTS — see the sibling script's own rationale: the full set (thousands of
    # signatures) is what the offline checker needs (a wrong reader breaks a page as thoroughly
    # as a wrong entrypoint), but shipping that to a browser for a hover tooltip is not a trade
    # worth making, and the tooltip only ever looks up Talos entrypoints and INFO_ previews.
    FULL.parent.mkdir(parents=True, exist_ok=True)
    FULL.write_text(json.dumps(sigs, indent=0, sort_keys=True), encoding="utf8")
    bundled = re.compile(r'\.([A-Za-z0-9|_-]*\|C{1,2}p?_[A-Za-z0-9]+|INFO_[A-Za-z0-9|_-]+)$')
    sigs = {k: v for k, v in sigs.items() if bundled.search(k)}

    lines = [
        "// ─── Pact Signatures — GENERATED FILE ───────────────────────────────",
        "//",
        "// DO NOT EDIT — generated by `python3 scripts/generate-pact-signatures.py`.",
        "//",
        "// Every Talos client entrypoint (`|C_`, `|CC_`) and every `INFO_` preview, mapped to",
        "// its parameter names IN ORDER, read straight out of the Pact sources.",
        "//",
        "// The execution tooltip (`zbom/cfm/ExecutionTooltip.tsx`) renders these so a button",
        "// states its real API before you press it. They come from the contract rather than a",
        "// hand-kept copy for the same reason this package's own builders drifted in the",
        "// 2026-09-26 \"complete rehaul\" round: a copy goes stale silently, and a tooltip built",
        "// on a stale copy would confirm a wiring that is wrong — the one thing it exists to",
        "// catch.",
        "",
        "export const PACT_SIGNATURES: Readonly<Record<string, readonly string[]>> = {",
    ]
    for key in sorted(sigs):
        args = ", ".join(f'"{a}"' for a in sigs[key])
        lines.append(f'  {json.dumps(key)}: [{args}],')
    lines += ["};", "",
              "/** Parameter names for a `MODULE.FUNCTION`, or null when the contract has no such",
              " *  member — which is itself the answer a tooltip should show. */",
              "export function signatureOf(qualified: string): readonly string[] | null {",
              "  return PACT_SIGNATURES[qualified] ?? null;",
              "}", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf8")
    print(f"wrote {FULL.relative_to(PKG)} (checker, full, {os.path.getsize(FULL)} bytes) and "
          f"{OUT.relative_to(PKG)} ({len(sigs)} signatures, bundled)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
